# Default values for k6-loadtest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

parallelism: 2

image:
  repository: dmsqlczzz/k6-prometheus
  tag: "v0.3"

affinity: {}

createServiceAccount: true
serviceAccountName: k6-cronjob

cronjobSchedule: "00 * * * *"

k6_file: |
  import http from 'k6/http';
  import { check } from 'k6';
  import { sleep } from 'k6';

  export const options = {
    stages: [
      { target: 100, duration: '29m' },
      { target: 1, duration: '29m' }
    ],
  };

  export default function () {
    const incluster = http.get('http://www.naver.com');
    check(incluster, {
      'incluster http response status code is 200': incluster.status === 200,
    });

    sleep(1);
  }
